# Catatan Sesi 4

# PYTN-KS08-017

Andreas Dimas Christanto

## LIST VS NUMPY

LIST

In [3]:
def pythonsum(n):
    a = b = list(range(n))
    c = []
    for i in range(len(a)):
        x = a[i] ** 2
        y = b[i] ** 3
        c.append(x + y)
    return c

c = pythonsum(10)
print(c)


[0, 2, 12, 36, 80, 150, 252, 392, 576, 810]


## NUMPY

In [7]:
import numpy as np 
def  numpysum(n):
    a = np.arange(n) **2
    b = np.arange(n) **3
    c= a+b
    return c
c = pythonsum(10) 
c
    

[0, 2, 12, 36, 80, 150, 252, 392, 576, 810]

Numpy Basic

In [8]:
# Often to user to use
import numpy as np 
np.array([1,2,3])

array([1, 2, 3])

In [11]:
# Not Recomended
from numpy import *
array([1,1,1])

array([1, 1, 1])

In [15]:
array1 = np.arange(101)
array1

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [18]:
array2 = list(range(100))
array2

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [20]:
# np.set_printoptio(threshold=10) >> i dont know mr.Gunawan write a code. But think this code just to show of the brief print like [ 0 1 2 ... 97 98 99]

Create An Ndarrays

In [22]:
import numpy as np

my_list = list(range(5))
my_list
print(type(my_list))

<class 'list'>


In [ ]:
# change list to array
array3 = np.array(my_list)
print(type(array3))
array3

In [25]:
print(np.arange(4))
print(np.arange(1,10))
print(np.arange(2,10,2)) # 2 = START ; 10 = LAST ; 2 RANGE

[0 1 2 3]
[1 2 3 4 5 6 7 8 9]
[2 4 6 8]


Add, Remove, and Sort
> np.append()
> np.delete()
> np.sort()

In [32]:
# Add Array
ex_array = np.array([1,2,4,3])
ex_array = np.append(ex_array,[16])
ex_array
# Delete Array
ex_array = np.delete(ex_array,[0])
ex_array
# Sort Array
ex_array = np.sort(ex_array)
ex_array

array([ 2,  3,  4, 16])

In [43]:
import numpy as np 
dimension2 = [[0,1],[2,3]]
print(dimension2)
ar_dimension2 = np.array(dimension2)
print(ar_dimension2.ndim) # dimension
print(ar_dimension2.shape) # shape
print(ar_dimension2.size) # Total Element

[[0, 1], [2, 3]]
2
(2, 2)
4


In [1]:
import numpy as np 
dimension3 = np.array([[[1,2,3,4],
                        [3,1,2,2]],
                       [[2,1,2,2],
                        [2,12,1,2]],    
                       [[1,3,1,2],
                        [2,1,3,2]]])
dimension3
## 29.00

array([[[ 1,  2,  3,  4],
        [ 3,  1,  2,  2]],

       [[ 2,  1,  2,  2],
        [ 2, 12,  1,  2]],

       [[ 1,  3,  1,  2],
        [ 2,  1,  3,  2]]])

In [8]:
dimension3[0,1]=0
dimension3

array([[[ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 2,  1,  2,  2],
        [ 2, 12,  1,  2]],

       [[ 1,  3,  1,  2],
        [ 2,  1,  3,  2]]])

Sorting Array 

In [38]:
dta = np.array([[0,10,2,3],
              [2,3,2,2]])
dta

array([[ 0, 10,  2,  3],
       [ 2,  3,  2,  2]])

In [40]:
print(dta)
print("-"*20)
dta.sort(axis = 0)
print(dta)
# with use axis = 0 we can got sort top to bottom
# with use axis = 1 we can got sort bottom to top

[[ 0  2  3 10]
 [ 2  2  2  3]]
--------------------
[[ 0  2  2  3]
 [ 2  2  3 10]]


In [32]:
print(dta)
print("-"*20)
dta.sort(axis = 1)
print(dta)
# with use axis = 1 we can got sort at coloum

[[ 0  2  2  3]
 [ 2  2  3 10]]
--------------------
[[ 0  2  2  3]
 [ 2  2  3 10]]


 Structure Array 

In [56]:
dtype = [('name','S10'),
           ('work','S10'),
           ('Age',int),
           ('status',"S10")]
dtype

[('name', 'S10'), ('work', 'S10'), ('Age', int), ('status', 'S10')]

In [53]:
data_peop = [('Andreas Dimas C','Pertamina',23,'Single'),
            ('Vincensius Gede C','Doktor',25,'Single')
            ]
data_peop

[('Andreas Dimas C', 'Pertamina', 23, 'Single'),
 ('Vincensius Gede C', 'Doktor', 25, 'Single')]

In [57]:
data_our = np.array(data_peop, dtype=dtype)
print(data_our)

[(b'Andreas Di', b'Pertamina', 23, b'Single')
 (b'Vincensius', b'Doktor', 25, b'Single')]


In [58]:
datasort = np.sort(data_our,order='name')
datasort

array([(b'Andreas Di', b'Pertamina', 23, b'Single'),
       (b'Vincensius', b'Doktor', 25, b'Single')],
      dtype=[('name', 'S10'), ('work', 'S10'), ('Age', '<i4'), ('status', 'S10')])

In [61]:
np.sort(data_our, order=['Age'])

array([(b'Andreas Di', b'Pertamina', 23, b'Single'),
       (b'Vincensius', b'Doktor', 25, b'Single')],
      dtype=[('name', 'S10'), ('work', 'S10'), ('Age', '<i4'), ('status', 'S10')])

In [63]:
npzero = np.zeros(10)
npzero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [66]:
npones = np.ones(20)
npones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [68]:
# empty array 
# the function of this code to blbbaa
# ?
np.empty(2)

array([-4.01897791e-050,  1.94766528e+198])

In [77]:
dzeros = np.zeros((3,2,4))
# 3 dimension ; 2 axis ; 4 coloum

In [80]:
a =dzeros.shape
b =dzeros.ndim
print(a ,b)

(3, 2, 4) 3


## ReShape

Make a new shape or convert shape to shape
numpy.reshape(a, (newshape,order))

In [9]:
import numpy as np
a = np.arange(6)
print(a)
print('-'*8)
b = a.reshape(2,3)
print(b)
print('-'*8)
c = a.reshape(3,2)
print(c)

[0 1 2 3 4 5]
--------
[[0 1 2]
 [3 4 5]]
--------
[[0 1]
 [2 3]
 [4 5]]


In [10]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

## Convert 1D to 2D

np.newaxis
np.expand_dims


In [15]:
variabel = np.array([1,2,3,4,5,6])
variabel.shape
print(variabel)
variabel.ndim

[1 2 3 4 5 6]


1

In [13]:
var2 = variabel[np.newaxis]
print(var2.shape)
print(var2)
var2.ndim

(1, 6)
[[1 2 3 4 5 6]]


2

In [19]:
var3 = var2[np.newaxis]
print(var3)
var3.ndim

[[[1 2 3 4 5 6]]]


3

In [21]:
# No Matter 
row_vector = variabel[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


## Indexing and Slicing

In [22]:
data = np.array([1,2,3])
print(data)
# basic 
print(data[0],data[1])

[1 2 3]
1 2


In [24]:
 print(data[0:2])

[1 2]


In [25]:
print(data[1:])

[2 3]


In [29]:
print(data[-2:]) # -2:-1 ; -1nya optional

[2 3]


In [42]:
import numpy as np
a = np.array([[[2,3,4,5,6,7],
            [3,3,3,3,3,3],
            [4,111,1,14,2,3]]])
print(a)

[[[  2   3   4   5   6   7]
  [  3   3   3   3   3   3]
  [  4 111   1  14   2   3]]]


In [49]:
print(a[a<10])
asu = a < 10
print(a[asu])
print(a[a%2==0])

[2 3 4 5 6 7 3 3 3 3 3 3 4 1 2 3]
[2 3 4 5 6 7 3 3 3 3 3 3 4 1 2 3]
[ 2  4  6  4 14  2]


In [51]:
c = a[(a>2) & (a<11)]
print(c)

[3 4 5 6 7 3 3 3 3 3 3 4 3]


## Creating Array from Existing Data

In [52]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [62]:
arr1 = np.array([[1,1],
               [2,2]])
arr2 = np.array([[3,3],
               [4,4]])
arr3 = np.array([[5,5],
               [6,6]])
np.vstack((arr1,arr2,arr3))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5],
       [6, 6]])

In [66]:
a = np.array(([1],[2],[3]))
b = np.array(([5],[5],[4]))
c = np.array(([1],[2],[3]))
np.hstack((a,b,c))

array([[1, 5, 1],
       [2, 5, 2],
       [3, 4, 3]])

In [79]:
arrsplit = np.array(([1,2,2],
                    [10,3,11]))
print(arrsplit)
np.hsplit(arrsplit,3)

[[ 1  2  2]
 [10  3 11]]


[array([[ 1],
        [10]]),
 array([[2],
        [3]]),
 array([[ 2],
        [11]])]

In [81]:
np.vsplit(arrsplit,2)

[array([[1, 2, 2]]), array([[10,  3, 11]])]

In [87]:
a = np.array(([1,2,3,4],[5,2,1,1],[1,1,1,1]))
b = a.view()
b
c = a.copy()
c

array([[1, 2, 3, 4],
       [5, 2, 1, 1],
       [1, 1, 1, 1]])

# Copying

In [ ]:
# 
x = [0,1]
y = [2,3]
z = x
print(x)
z[0]=5 
print(x) # So if you copy like x = z , if u change z so that x change too
# so how to change z but not change x 
# we can do like that
z = y.copy()
z[0]=1
print(z)
print(y) # proven !


# Basic Array Operation

In [90]:
a = np.array([1,2,3,4])
a.sum()

10

In [93]:
b = np.array([[1, 3], [2, 2]])
b

array([[1, 3],
       [2, 2]])

In [94]:
b.sum(axis = 0) # add coloum

array([3, 5])

In [96]:
b.sum(axis = 1) 

array([4, 4])

# Broadcasting 

In [98]:
print(b)
print(b*1.2)

[[1 3]
 [2 2]]
[[1.2 3.6]
 [2.4 2.4]]


# Function

Ones

In [101]:
b = np.ones((1,2)) # 1 axis 2 coloum
b
#print array([[1., 1.]])

array([[1., 1.]])

Full

In [102]:
c = np.full((2,2),7) # 2 axis 2 coloum 7 its value
c

array([[7, 7],
       [7, 7]])

eye

In [104]:
d = np.eye(10)
d

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

Random

In [118]:
m = np.random.seed(0)
print(m)
print(np.random.randint(10)) # if there is np.random.seed(0) the value of randint cantt to change

None
5


In [116]:
print(np.random.randint(10)) # if there is not seed that is can change to change 

None


In [3]:
import numpy as np 
np.random.seed(1)
random_arr = np.random.randint(3, high=100,
                              size=(2,2)) # randint(low,heigh,size)
print(random_arr)
# OR
random_as = np.random.randint(3,100,(2,2))
random_as

[[40 15]
 [75 12]]


array([[78,  8],
       [82, 67]])

In [7]:
# 1:18:00
a= random_arr.min()
b= random_arr.std()
c= random_arr.min(axis=1)
print(random_arr)
print(a,b,c)

[[40 15]
 [75 12]]
12 25.26361019331956 [15 12]


In [9]:
print(random_arr.argmin)
print(random_arr.argmax)

<built-in method argmin of numpy.ndarray object at 0x0000019C3DF85510>
<built-in method argmax of numpy.ndarray object at 0x0000019C3DF85510>


#  Save Array into file

In [16]:
A = np.array([[1,12,12,12],
              [12,121,12,1],
              [12,12,12,12]])
print(A)

[[  1  12  12  12]
 [ 12 121  12   1]
 [ 12  12  12  12]]


In [19]:
np.save("myarr.npy",A)


In [22]:
ase = np.load('myarr.npy')

In [23]:
print(ase)

[[  1  12  12  12]
 [ 12 121  12   1]
 [ 12  12  12  12]]


# Case Study

10 Buah botol minum akan dibuat untuk menyimpan air dengan jari jari dan tinggi yang berbeda - beda. Besaran jari jari dan  botol adalah bilangan bulat kisaran 7 sampai dengan 20 cm

Tentukan :
1. Volume Air yang dapat disimpan di setiap botol
2. Total volume air yang tersimpan dalam sebuah botol 
3. Botol mana yang volum air terkecil dan temukan volumnenya 
4. Botol mana yang menampung volume air terbesar dan temukan volume airnya.
5. Rata rat volume yang dapat di tampung di tiap botol


Solusi :
1. Lakukan generate tinggi botol dan jari jari 
2. Punya batasan 7 sampai 20, kemudian sebanyak 10 dengan kata lain harus mengenarate sebanyak 20
3. Membentuk botol sebanyak 10 buah ( tinggi dan jari jari)
4. Setelah terbentuk botol mencari volume air masing botol volume air = (Pi x r^2 x t ) untuk numpy pi = np.pi
5. Mencari total volume air dalam semua botol sum 
6. Mencari botol yang terkecil dan temukan volumenya
7. mencari botol yang terbesar dan temukan volumenya
8. Mencri rat rata dengan mean 


# Dot Product

In [24]:
np.dot?

In [26]:
np.dot(3,8)

24

# NP read csv

In [27]:
import csv
data = []

with open('')